[features]
seeds = false
skip-lint = false
[programs.devnet]
counter_anchor = "21spMzeE6F9r651WBWSJdJS4X6R59jPrTxPdFtVa5y16"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/imentus/Desktop/keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
