[features]
seeds = false
skip-lint = false
[programs.devnet]
counter_anchor = "4AK9rQH7e9NoduAwu6vtbCkbYPkEnYJsPdrs3ATPhwKJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/imentus/Desktop/keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
